<?php

$labels = array();

// mail

$labels['folder_contact'] = 'Dossier Contact';

$labels['folder_create'] = 'Créer un dossier';
$labels['folder_delete'] = 'Supprimer un dossier';
$labels['folder_rename'] = 'Renommer un dossier';
$labels['folder_locate'] = 'Chercher un dossier';

$labels['folder_purge'] = 'Vider un dossier';

$labels['folder_read_this'] = 'Marquer ce dossier comme lu';
$labels['folder_read_tree'] = 'Marquer ce dossier et tous ses sous-dossiers comme lu';

$labels['show_all'] = 'Montrer tout';
$labels['show_active'] = 'Montrer les dossiers actifs';
$labels['show_favorite'] = 'Montrer les dossiers favoris';

$labels['folder_select'] = 'Ajouter ce dossier aux favoris';
$labels['folder_unselect'] = 'Enlever ce dossier des favoris';

$labels['reset_selected'] = 'Ré-initialiser ce(s) dossier(s)';
$labels['reset_transient'] = 'Ré-initialiser le(s) dossier(s) temporaire(s)';

$labels['status_title'] = 'Folder view...';

$labels['folder_expand_all'] = 'Tout déployer';
$labels['folder_collapse_all'] = 'Tout reployer';

$labels['folder'] = 'Dossier';

$labels['reset'] = 'Ré-initialiser';
$labels['apply'] = 'Appiquer';
$labels['cancel'] = 'Annuler';
$labels['select'] = 'Selectionner';
$labels['search'] = 'Chercher';

$labels['source'] = 'Source';
$labels['target'] = 'Cible';

$labels['create'] = 'Créer';
$labels['delete'] = 'Supprimer';
$labels['rename'] = 'Renommer';
$labels['locate'] = 'Chercher';

$labels['parent'] = 'Parent';
$labels['header'] = 'Entête';
$labels['format'] = 'Format';
$labels['type'] = 'Type';
$labels['full_name'] = 'Nom complet';
$labels['mail_addr'] = 'Adresse de messagerie';

$labels['message_copy'] = 'Copier vers le dossier';
$labels['message_move'] = 'Déplacer vers le dossier';

// settings

$labels['plugin_folder_menu'] = 'Plugin: Menu';

$labels['activate_plugin'] = 'Activer ce plugin';

$labels['enable_logging'] = 'Activer les traces';
$labels['enable_refresh'] = 'Activer l\'auto-rafraichissement des sous-dossiers';
$labels['enable_folder_list_context_menu'] = 'Activer le context menu';
$labels['enable_folder_list_control_menu'] = 'Activer la fonction "gestion" du context menu';
$labels['enable_message_list_context_menu'] = 'Activer la fonction  "liste des messages"';

$labels['feature_choice'] = 'Activer les fonctionnalités';

$labels['filter_active'] = 'Liste des filtres "actifs"';
$labels['filter_favorite'] = 'Liste des filtres "favoris"';

$labels['predefined_list'] = 'Liste des filtres prédéfinis';
$labels['contact_folder_format_list'] = 'Format des Contacts';

$labels['transient_expire_mins'] = 'Expiration des dossiers temporaires (mins)';

?>
